doctrine:
    dbal:
        
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            mysql_entry:
                url: '%env(resolve:DATABASE_URL)%'
            entry_number:
                url: '%env(resolve:DATABASE_URL)%'
            oracle:
                url: '%env(resolve:ORACLE_DATABASE_URL)%'
            oracle_prod:
                url: '%env(resolve:ORACLE_PRODUCTION_DATABASE_URL)%'
                
        default_connection: default
       
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    default:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            oracle:
                connection: oracle
                mappings:
                    default:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/oracle'
                        prefix: 'App\Entity\oracle'
                        alias: oracle
            oracle_prod:
                connection: oracle_prod
                mappings:
                    default:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/oracle'
                        prefix: 'App\Entity\oracle'
                        alias: oracle_prod
            mysql_entry:
                connection: mysql_entry
                mappings:
                    default:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App    
            entry_number:
                connection: entry_number
                mappings:
                    default:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App        			
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
